# 异常

## 概念

在使用计算机语言进行项目开发的过程中，即使程序员把代码写得尽善尽美(代码大全)，在系统的运行过程中仍然会遇到一些问题，因为很多问题不是靠代码能够避免的，比如：客户输入数据的格式，读取文件是否存在，网络是否始终保持通畅等等。
异常：在Java语言中，将程序执行中发生的不正常情况称为“异常”。
(开发过程中的语法错误和逻辑错误不是异常)

## 异常的类型

**Java程序在执行过程中所发生的异常事件可分为两类：**

- Error: Java虚拟机(JVM)无法解决的严重问题。如：JVM系统内部错误、资源耗尽等严重情况。一般不编写针对性的代码进行处理。(放任其自生自灭,一般情况下我们不管)
- Exception: 其它因编程错误或偶然的外在因素导致的一般性问题，可以使用针对性的代码进行处理。例如：
 - 空指针访问
 - 试图读取不存在的文件
 - 网络连接中断

## 异常的处理

- 第一种: 遇到错误就终止程序的运行。
- 第二种: 由程序员在编写程序时，就考虑到错误的检测、错误消息的提示，以及错误的处理。(开发当中应该考虑的情况)

> 捕获错误最理想的是在编译期间，但有的错误只有在运行时才会发生。比如：除数为0，数组下标越界等

## Exception分类

编译时异常和运行时异常

**异常继承图**

![](http://ovsf6lwoc.bkt.clouddn.com/image/jpg/201709242334.png)

## Exception的类型

- 运行时异常是指编译器不要求强制处置的异常。一般是指编程时的逻辑错误，是程序员应该积极避免其出现的异常。java.lang.RuntimeException类及它的子类都是运行时异常。对于这类异常，可以不作处理，因为这类异常很普遍，若全处理可能会对程序的可读性和运行效率产生影响。
运行时异常是我们未来开发中最最最经常应该使用的异常
- 编译时异常是指编译器要求必须处置的异常。即程序在运行时由于外界因素造成的一般性异常。编译器要求java程序必须捕获(必须要处理该异常)或声明所有编译时异常。对于这类异常，如果程序不处理，可能会带来意想不到的结果.

**运行时异常(不受审查异常)**

- 越界异常

```java
public class 数组越界异常_运行时异常 {

    public static void main(String[] args) {
        //没有提示其需要处理的异常,为运行时异常(不受审查异常)
        String[] arrs = {"悟空","八戒","唐僧"};

        for(int i=0;i<4;i++){
            System.out.println(arrs[i]);
		//java.lang.ArrayIndexOutOfBoundsException:
        }
        //如果出错了下面的代码将不在运行

        String shxt = "hello";

        System.out.println(shxt.charAt(100));
        //java.lang.StringIndexOutOfBoundsException: String index out of range: 100

    }

}
```

- 空指针异常

```java
package com.gobha.exception01;

public class 空指针异常_运行时异常2 {

    public static void main(String[] args) {
        String str = null;

        System.out.println(str.isEmpty());

        Person person = new Person();

        person = null;

        person.say();

    }

}

class Person{
    public void say(){
        System.out.println("Hello World");
    }
}
```

- 运算异常

```java
package com.gobha.exception01;

public class 运算异常_运行时异常 {

    public static void main(String[] args) {
        int a = 100;

        System.out.println(a/A.num);
    }

}

class A{

    public static int num;
}
```

`java.lang.ArithmeticException: / by zero`

- 类型转换异常

```java
package com.gobha.exception01;

import java.util.Date;

public class 类型转换异常_运行时异常 {

    public static void main(String[] args) {
        Object obj = new Date();

        B bb = (B)obj;//转换失败
    }

}

class B{

}
```

`Exception in thread "main" java.lang.ClassCastException: java.util.Date cannot be cast to com.gobha.exception01.B`

## 异常处理机制

在编写程序时，经常要在可能出现错误的地方加上检测的代码，如进行x/y运算时，要检测分母为0，数据为空，输入的不是数据而是字符等。过多的分支会导致程序的代码加长，可读性差。因此采用异常机制。

Java异常处理Java采用异常处理机制，将异常处理的程序代码集中在一起，与正常的程序代码分开，使得程序简洁，并易于维护。

**Java提供的是异常处理的抓抛模型。**

Java程序的执行过程中如出现异常，会生成一个异常类对象，该异常对象将被提交给Java运行时系统，这个过程称为抛出(throw)异常。异常对象的生成由虚拟机自动生成：程序运行过程中，虚拟机检测到程序发生了问题，如果在当前代码中没有找到相应的处理程序，就会在后台自动创建一个对应异常类的实例对象并抛出——自动抛出由开发人员手动创建：Exception exception = new ClassCastException();——创建好的异常对象不抛出对程序没有任何影响，和创建一个普通对象一样。

```java
public class 抓模型_捕获异常 {

    public static void main(String[] args) {
        int a = 100;
        try{
            System.out.println(a/A.num);//正常代码
        }catch(ArithmeticException e){
            System.out.println("运行错误,原因可能为:"+e);//异常处理的代码
        }
    }
}
class A{
    public static int num;
}
```

**如果对异常不处理**

模拟环境

如果一个方法内抛出异常，该异常对象会被抛给调用者方法中处理。如果异常没有在调用者方法中处理，它继续被抛给这个调用方法的上层方法。这个过程将一直继续下去，直到异常被处理。这一过程称为捕获(catch)异常。

> 如果一个异常回到main()方法，并且main()也不处理，则程序运行终止。

代码说明

```java
public class 上层调用者 {
    public static void 上层方法(){
        调用者.调用方法();
    }
    public static void main(String[] args){
        上层方法();//抛给系统处理或者自己使用try...catch操作
    }
}

public class 调用者 {
    public static void 调用方法(){
        使用方法.say(); //没有做处理,继续抛给上层调用者
    }
}

public class 使用方法 {
    public static void say(){
        //运行时异常
        //System.out.println(10/0);
        RuntimeException re = new NullPointerException("我是空指针异常");
        //实例化好了,但是你没有抛出
        throw re;//抛出异常 
    }
}
```

**通常只能处理Exception，而对Error无能为力。**

### 捕获异常

异常处理是通过`try-catch-finally`语句实现的。

```java
try{
	//可能产生异常的代码
}
catch( ExceptionName1 e ){
	//当产生ExceptionName1型异常时的处置措施
}
catch( ExceptionName2 e ){
	//当产生ExceptionName2型异常时的处置措施
}
finally{
	//无论是否发生异常，都无条件执行的语句

    }
 ]
```

```java
public class 捕获异常01 {
    public static void main(String[] args) {
        try{
            String shxt = null;
			System.out.println(shxt.isEmpty());

            String[] arrs = {"悟空","八戒","唐僧"};
            for(int i=0;i<2;i++){
                System.out.println(arrs[i]);
            }
        }catch(NullPointerException e){
            System.out.println("空指针异常了,你的代码有错误:"+e);
        }catch(ArrayIndexOutOfBoundsException e){
            System.out.println("数组越界了,你的程序错误:"+e);
        }finally{
            System.out.println("finally---->不管程序是否正确,该段代码都会执行");
            //永远不要在这个位置写return
        }
    }
}
```

捕获异常的有关信息：与其它对象一样，可以访问一个异常对象的成员变量或调用它的方法。

- getMessage() 获取异常信息，返回字符串。
- printStackTrace() 获取异常类名和异常信息，以及异常出现在程• 序中的位置。返回值void。
- 可以尽量使用printStackTrace()输出错误的信息。
- printStackTrace()只是输出,没有做任何处理。
- 如果出现异常了,从下往上看。
- 前面使用的异常都是RuntimeException类或是它的子类，这些类的异常的特点是：
 - 即使没有使用try和catch捕获，Java自己也能捕获，并且编译通过 ( 但运行时会发生异常使得程序运行终止 )。
 - 如果抛出的异常是IOException等类型的非运行时异常，则必须捕获，否则编译错误。
- 必须处理编译时异常，将异常进行捕捉，转化为运行时异常

```java
public class 使用方法 {
    public static void say(){
        Exception e = new IOException("IO编译时异常");
        //实例化好了,但是你没有抛出
        try {
            throw e;
        } catch (Exception e1) {
            // 把编译异常转换为运行时异常
            RuntimeException re = new RuntimeException(e1);
            throw re;
        }//抛出异常

    }

}

public class 调用者 {
    public static void 调用方法(){
        使用方法.say(); //没有做处理,继续抛给上层调用者
    }
}

public class 上层调用者 {

    public static void 上层方法(){
        调用者.调用方法();
    }
    public static void main(String[] args){
        try{
            上层方法();//抛给系统处理,最终停止运行 或者 自己使用try...catch操作
        }catch(NullPointerException e){
            e.printStackTrace();
        }
    }

}
```

### 抛出声明异常

- 声明抛出异常是Java中处理异常的第二种方式(不处理)
- 如果一个方法(中的语句执行时)可能生成某种异常，但是并不能确定如何处理这种异常，则此方法应显示地声明抛出异常，表明该方法将不对这些异常进行处理，而由该方法的调用者负责处理。
- 在方法声明中用throws语句可以声明抛出异常的列表，throws后面的异常类型可以是方法中产生的异常类型，也可以是它的父类。
声明抛出异常举例：

```java
public void readFile(String file)  throws FileNotFoundException {
    // 读文件的操作可能产生FileNotFoundException类型的异常
    FileInputStream fis = new FileInputStream(file);

    }
```

## 异常重写方法的规则

**重写方法不能抛出比被重写方法范围更大的异常类型。**

```java
public class Parent {

    public void test01()throws NullPointerException{

    }

}

public class Child  extends Parent{

    public void test01()throws IOException{

    }

}
```

## 自定义异常

```java
public class 测试代码 {
    static void methodA() {
        try {
            System.out.println("进入方法A");
            throw new RuntimeException("制造异常");
        } finally {
            System.out.println("用A方法的finally");
        }
    }

    static void methodB() {
        try {
            System.out.println("进入方法B");
            return;
        } finally {
            System.out.println("调用B方法的finally");
        }
    }

    public static void main(String[] args) {
        try {
            methodA();
        } catch (Exception e) {
            System.out.println(e.getMessage());//实际上没有做处理
            //throw new RuntimeException(e.getMessage());//用的这段代码
        }
        methodB();
    }

}
```